[start]
command:/usr/local/bin/php /usr/local/opnsense/scripts/coretun/sync_gateway.php;/usr/local/opnsense/scripts/coretun/service_control.py start
parameters:
type:script
message:starting coretun

[stop]
command:/usr/local/opnsense/scripts/coretun/service_control.py stop
parameters:
type:script
message:stopping coretun

[restart]
command:/usr/local/bin/php /usr/local/opnsense/scripts/coretun/sync_gateway.php;/usr/local/opnsense/scripts/coretun/service_control.py restart
parameters:
type:script
message:restarting coretun
description:Restart Coretun

[reconfigure]
command:/usr/local/bin/php /usr/local/opnsense/scripts/coretun/sync_gateway.php;/usr/local/opnsense/scripts/coretun/service_control.py reconfigure
parameters:
type:script
message:reconfiguring coretun

[reload]
command:/usr/local/bin/php /usr/local/opnsense/scripts/coretun/sync_gateway.php;/usr/local/opnsense/scripts/coretun/service_control.py reconfigure
parameters:
type:script
message:reloading coretun

[status]
command:/usr/local/opnsense/scripts/coretun/service_control.py status
parameters:
type:script_output
message:request coretun status

[log]
command:/usr/local/opnsense/scripts/coretun/show_log.py
parameters:
type:script_output
message:request coretun log

[import]
command:/usr/local/opnsense/scripts/coretun/import_uris.py
parameters:%s
type:script_output
message:importing proxy URIs

[setup]
command:/usr/local/opnsense/scripts/coretun/setup.sh
parameters:
type:script
message:setting up coretun dependencies

[subscription_update]
command:/usr/local/bin/php /usr/local/opnsense/scripts/coretun/subscription_sync.php
parameters:%s
type:script_output
message:updating coretun subscriptions
description:Update Coretun subscriptions

[subscription_watchdog]
command:/usr/local/opnsense/scripts/coretun/subscription_watchdog.php
parameters:
type:script_output
timeout:120
message:coretun connectivity watchdog
description:Coretun connectivity watchdog

[subscription_probe]
command:/usr/local/opnsense/scripts/coretun/probe_servers.py
parameters:
type:script_output
timeout:120
message:probing coretun servers
description:Probe Coretun servers for connectivity and latency
